name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16, 18, 20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      working-directory: ./app
        
    - name: Fix line endings
      run: |
        # Convert CRLF to LF for all text files
        find . -type f -name "*.js" -o -name "*.json" -o -name "*.md" -o -name "*.yml" -o -name "*.yaml" | xargs dos2unix || true
      working-directory: ./app
        
    - name: Run linting
      run: npm run lint
      working-directory: ./app
        
    - name: Run tests
      run: npm test
      working-directory: ./app
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: matrix.node-version == '18'
      with:
        file: ./app/coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  security:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      working-directory: ./app
        
    - name: Fix line endings
      run: |
        # Convert CRLF to LF for all text files
        find . -type f -name "*.js" -o -name "*.json" -o -name "*.md" -o -name "*.yml" -o -name "*.yaml" | xargs dos2unix || true
      working-directory: ./app
        
    - name: Run security audit
      run: npm audit --audit-level moderate
      working-directory: ./app
        
    - name: Run Snyk security scan
      run: |
        cd app
        npx snyk test --severity-threshold=high || true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true
      # Note: This step requires a SNYK_TOKEN secret to be configured
      # You can get a free Snyk account at https://snyk.io/
      # Or remove this step if you don't want to use Snyk

  build:
    runs-on: ubuntu-latest
    needs: [test, security]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      working-directory: ./app
        
    - name: Fix line endings
      run: |
        # Convert CRLF to LF for all text files
        find . -type f -name "*.js" -o -name "*.json" -o -name "*.md" -o -name "*.yml" -o -name "*.yaml" | xargs dos2unix || true
      working-directory: ./app
        
    - name: Build application
      run: npm run build
      working-directory: ./app
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: |
          app/dist/
          app/build/
        retention-days: 7
